[package]
name = "kash2"
version = "0.1.0"
authors = ["max <mx.sht06@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
crossterm = "0.25"
clap = "4.0"
anyhow = "1.0"
nom = "7.1"
regex = "1.7"
nom_locate = "4.0"
itoa = "1.0"
